language: python

python:
- "3.5"
- "pypy3.5"
- "3.6"
- "pypy3.6"

install:
- pip install -r requirements-dev.txt

script:
- python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests

after_success:
- codecov

branches:
  only:
  - master
  - dev
